/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function SceneTwo({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/BpBgE3a47CP3dLjs/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#e7e7e7']} />
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <mesh
            name="MASK"
            geometry={nodes.MASK.geometry}
            material={materials['MASK Material']}
            castShadow
            receiveShadow
            position={[-29.47, 5, -491]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            name="LIGHT-SPHERE2"
            geometry={nodes['LIGHT-SPHERE2'].geometry}
            material={materials['LIGHT-SPHERE2 Material']}
            castShadow
            receiveShadow
            position={[-139.22, 221.18, -569.19]}
            rotation={[0, 0.59, 0]}
          />
          <mesh
            name="LIGHT-SPHERE"
            geometry={nodes['LIGHT-SPHERE'].geometry}
            material={materials['LIGHT-SPHERE Material']}
            castShadow
            receiveShadow
            position={[-22.9, -79.92, -448.55]}
          />
          <mesh
            name="GLASS-SPHERE"
            geometry={nodes['GLASS-SPHERE'].geometry}
            material={materials['GLASS-SPHERE Material']}
            castShadow
            receiveShadow
          />
          <OrthographicCamera name="1" makeDefault={true} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
        </scene>
      </group>
    </>
  )
}
