/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useRef } from 'react'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/3rOki-2CjQJSHlzw/scene.splinecode')

  useFrame((state, delta) => (ref.current.rotation.x += 0.0001) + (ref.current.rotation.y += -0.003))
  const ref = useRef()

  return (
    <>
      <color attach="background" args={['#efeaf1']} />
      <group {...props} dispose={null} ref={ref}>
        <scene name="Scene">
        <mesh
            name="Cylinder"
            geometry={nodes.Cylinder.geometry}
            material={materials['Cylinder Material']}
            castShadow
            receiveShadow
            rotation={[1, -1, -1.5]}
            scale={1}
          />
        </scene>
      </group>
    </>
  )
}
